# Hugo variables
#
baseurl = "https://interwebworld.co.uk/"
languageCode = "en-us"
title = "Interweb World"
theme = "typewriter"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 10
# optionally override the site's footer with custom copyright text
# copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
#googleAnalytics = "UA-123-45"
#disqusShortname = "XYW"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Gerard McGarry"
  url = "https://gerardmcgarry.com"

[[menu.sidebar]]
  name = "Interweb World"
  url = "https://interwebworld.co.uk"

# custom navbar menu entry.   See the custom_navbar parameter below for
# details.

[[menu.navbar]]
  name = "Gerard"
  url = "https://gerardmcgarry.com"

[[menu.navbar]]
  name = "@gerrybot"
  url = "https://twitter.com/gerrybot"
  weight = -100

# Theme variables
#
[params]
  # Site author
  author = "Interweb World"

  # Description/subtitle for homepage (can be Markdown)
  description = "Talking technology and sharing knowledge"

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # customise the contents of the navbar at the top of the page.  The default
  # behaviour is to list all static pages not in the posts directory. When the
  # parameter below is set to true you will have to manually add entries to the
  # navbar, either by adding the following menu variable to the front matter of
  # the relevant pages
  #  menu = "navbar"
  # or by specifying menu entries in a similar way to the sidebar menu above.
  custom_navbar = true

  # Custom header image
  featureimage = "img/typewriter.jpg"

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    # about = "A place to talk about technology and things I'm distinctly passionate about. Static websites, fintech, AI, and much much more."

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "gerrybot"

  [params.sharingicons]
    # Hide the sharing icons on posts? (Default: false)
    hide = true

    # Optionally, set any of these to false to hide them:
    #facebook = true
    #googleplus = true
    #linkedin = true
    #twitter = true

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]
